#!/bin/bash

dir=`dirname $0`
phpda="$dir/vendor/bin/phpda"

if [ -z "$2" ]; then
	echo "USAGE: $0 <mediawiki-dir> [options] <yaml-file>"
	exit 1
fi

mwdir="$1"
shift

"$phpda" analyze --source "$mwdir/includes" "$@"
