#!/bin/bash
set -e -u

dir=`dirname $0`
phpda="$dir/vendor/bin/phpda"

if [ -z "$3" ]; then
	echo "SYNOPSIS: Runs phpda after generating a config file based on the command line parameters."
	echo "USAGE: $0 <analysis-name> <source-to-analyze> <output-format> [target-file]"
	exit 1
fi

if [ ! -d "$2" ]; then
	echo "not an existing directory: $2"
	exit 5
fi

name="$1"
source=`readlink -f "$2"`
format="$3"
target="${4:-$dir/www/report/$name.${format,,}}"
target=`readlink -f "$target"`

tmp=`mktemp -u`

echo "Analyzing $source to generate $format output."
php "$dir/src/twirl.php" formatter="$format" source="$source" target="$target"  < "$dir/$name.mustache" > "$tmp"

"$phpda" analyze "$tmp"

echo "$format output was written to $target"

rm -f "$tmp"

