#!/bin/bash

dir=`dirname $0`
metrics="$dir/src/metrics.php"
mwdir="${1:-.}"

if [ ! -d "$mwdir/includes" ]; then
	echo "$mwdir/includes does not exist or is not a directory."
	echo "Please specify the location of MediaWiki as the first parameter."
	exit 5
fi

"$dir/analyze" namespace-usage "$mwdir/includes" Svg
"$dir/analyze" namespace-usage "$mwdir/includes" Json

php "$metrics" "$dir/www/report/"

chmod -R a+rX "$dir/www/"
